version: build-{build}.{branch}
clone_folder: c:\gopath\src\github.com/Songmu/ecsched
shallow_clone: true
environment:
  GOPATH: c:\gopath
  GO111MODULE: on
install:
- copy c:\MinGW\bin\mingw32-make.exe c:\MinGW\bin\make.exe
- set PATH=%GOROOT%\bin;%GOPATH%\bin;c:\MinGW\bin;%PATH%
build: false
test_script:
- make lint
- make test
deploy: off
